name: SpotifyCatalogAPI tests project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Test:
    name: Execute Unittests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        datasource_type: [json, spotify_api]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run Unit Tests with datasource=${{ matrix.datasource_type }}
        run: |
          mvn test -q -Ddatasource.type=${{ matrix.datasource_type }}